name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-distutils

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov coverage-badge
          pip install .

      - name: Run tests with coverage
        run: |
          pytest --cov=your_package_name --cov-report=xml

      - name: Generate coverage badge
        run: |
          coverage-badge -o coverage.svg -f

      - name: Commit coverage badge
        if: github.event_name == 'push'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add coverage.svg
          git commit -m 'Update coverage badge'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}